name: run-on-docker
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [0]

    container: cypress/included:10.10.0

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          cd "db_api_ui" && yarn install --frozen-lockfile

      - name: Remove files
        run: |
          cd "db_api_ui" && yarn removeFile
        continue-on-error: false

      - name: Run Testing
        run: |
          cd "db_api_ui" && yarn runCucumber
        continue-on-error: false

      - name: Generate reports
        run: cd "db_api_ui" && yarn generalReport
        continue-on-error: false

      - name: Zip folder
        run: cd "db_api_ui" && yarn zipFolder
        continue-on-error: false
      
      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/report.html/html
          retention-days: 30

      - name: Send email
        run: cd "db_api_ui" && yarn sendEmail
        continue-on-error: false
